# Workflow to build Angular code and deploy it on S3 bucket

name: Deploy to S3 Bucket

on:
  push:
    branches:
    # only run this workflow when a PR is merged into or a commit is made directly to the production branch
    - production
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: ng test
      
    - name: Build
      run: ng build
      
    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/bakkcover_frontend s3://bakkcover
